<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Metaphor.Spectre</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Metaphor.Engine\Metaphor.Engine.vbproj" />
  </ItemGroup>

</Project>
